DEFAULT_EXTS = "epub,docx,pdf,html,htm,txt,md,markdown,odt,rtf"
DOWNLOAD_ATTEMPTS = 3
DOWNLOAD_RETRY_DELAY_SECONDS = 2
PACKAGE_INSTALL_ATTEMPTS = 3
PACKAGE_INSTALL_RETRY_DELAY_SECONDS = 2
MARKER_PACKAGE_NAME = "marker-pdf"
MINERU_PACKAGE_NAME = "mineru[all]"
PYPANDOC_PACKAGE_NAME = "pypandoc"
CORE_ENV_NAME = "core"
MARKER_ENV_NAME = "marker"
MINERU_ENV_NAME = "mineru"
MANAGED_ENVS_DIRNAME = ".venvs"
MARKER_INSTALL_HINT = "PDF conversion requires Marker CLI. The project attempted to install `marker-pdf`, but `marker_single` is still unavailable on PATH."
MINERU_INSTALL_HINT = "PDF conversion requires MinerU CLI. The project attempted to install `mineru[all]`, but `mineru` is still unavailable on PATH."
MARKER_SUPPORTED_OUTPUT_FORMAT = "markdown"
PANDOC_INPUT_SUFFIXES = {".epub", ".docx", ".html", ".htm", ".txt", ".md", ".markdown", ".odt", ".rtf"}
PDF_INPUT_SUFFIX = ".pdf"
PANDOC_TARGET_FORMAT = "commonmark_x"
PIP_DISABLE_VERSION_CHECK = "--disable-pip-version-check"
PIP_NO_INPUT = "--no-input"
PIP_QUIET = "--quiet"
AUTO_INSTALL_FAILURE_TEMPLATE = "Failed to auto-install {package} after {attempts} attempts: {detail}"
AUTO_INSTALL_POST_CHECK_TEMPLATE = "Installed {package}, but required executable `{executable}` is still unavailable on PATH."
PYPANDOC_IMPORT_ERROR = "pandoc is not installed, and automatic installation of `pypandoc` failed."
PANDOC_DOWNLOAD_ERROR = "pandoc is not installed, and automatic download via pypandoc failed after {attempts} attempts: {detail}"
PANDOC_POST_CHECK_ERROR = "pandoc download reported success, but no pandoc binary was found afterward"
